Repository frequenz-floss/frequenz-api-electricity-trading, pull requests merged in 2024-03, with the labels that each got.

#52 Fix DeliveryArea from and to pb methods
  RELEASE_NOTES.md
  py/frequenz/client/electricity_trading/_types.py
Labels: type:bug

#53 Use HasField method on protobuf messages
  RELEASE_NOTES.md
  py/frequenz/client/electricity_trading/_types.py
Labels: type:bug

#46 Refactor DeliveryDuration to Accept timedelta
  RELEASE_NOTES.md
  py/frequenz/client/electricity_trading/_types.py
Labels: part:docs

#54 Minor refactoring of DeliveryDuration using match-case
  py/frequenz/client/electricity_trading/_types.py
Labels: cmd:skip-release-notes

#47 Rename public_trade_lists and add documentation to PublicTrade message
  RELEASE_NOTES.md
  proto/frequenz/api/electricity_trading/v1/electricity_trading.proto
Labels: part:docs

#59 Remove _list suffixes in the client
  py/frequenz/client/electricity_trading/_client.py
  py/frequenz/client/electricity_trading/_types.py
Labels: cmd:skip-release-notes

#61 Remove ORDER_EXECUTION_OPTION_NONE from OrderExecutionOption
  RELEASE_NOTES.md
  proto/frequenz/api/electricity_trading/v1/electricity_trading.proto
  py/frequenz/client/electricity_trading/_types.py
Labels: part:docs, scope:breaking-change, type:tech-debt
