Repository frequenz-floss/frequenz-api-electricity-trading, pull requests merged in 2024-01, with the labels that each got.

#12 Bump yoheimuta/action-protolint from 1.0.0 to 1.2.0
  .github/workflows/ci.yaml
Labels: part:tooling

#16 Implement Electricity Trading API Client and type wrappers
  RELEASE_NOTES.md
  noxfile.py
  py/frequenz/client/electricity_trading/__init__.py
  py/frequenz/client/electricity_trading/_client.py
  py/frequenz/client/electricity_trading/_types.py
  pyproject.toml
Labels: part:docs, part:tooling

#18 Add unit conversion methods to Energy type
  RELEASE_NOTES.md
  py/frequenz/client/electricity_trading/_types.py
Labels: part:docs

#20 Revert #18 Add unit conversion methods to Energy type
  RELEASE_NOTES.md
  py/frequenz/client/electricity_trading/_types.py
Labels: part:docs

#21 Remove unnecessary optional keywords and add documentation
  proto/frequenz/api/electricity_trading/v1/electricity_trading.proto
Labels: cmd:skip-release-notes

#22 Reset release notes after the first release
  RELEASE_NOTES.md
Labels: part:docs

#23 Add missing types to __init__ file
  RELEASE_NOTES.md
  py/frequenz/client/electricity_trading/__init__.py
Labels: part:docs

#26 Minor changes to `__init__` and `_types.py`
  RELEASE_NOTES.md
  py/frequenz/client/electricity_trading/__init__.py
  py/frequenz/client/electricity_trading/_types.py
  py/frequenz/client/electricity_trading/py.typed
Labels: part:docs

#32 Fix bug type in EnergyMarketCodeType
  RELEASE_NOTES.md
  py/frequenz/client/electricity_trading/_types.py
Labels: part:docs
